name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
        
      - name: Install GCC
        run: apt get gcc

      - name: Build ARM64 binary
        run: CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build
        
      - name: Create release
        id: create_release
        uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary
        id: upload_assets
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: myapp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
