# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: debian-arm64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: debian-11.2
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build ARM64 binary
      run: CGO_ENABLED=1 GOARCH=arm64 go build

    - name: Create release
      id: create_release
      uses: taiki-e/create-gh-release-action@v1
      with:
        changelog: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload binary
      id: upload_assets
      uses: taiki-e/upload-rust-binary-action@v1
      with:
        bin: myapp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
